.travis.yml
Disable semantic release
- [] The commit message follows the
Semantic release is trying to run without creds, and failing.
Semantic release won't run. It will be enabled later when we're not working with 0.x releases.
=> ci: Disable semantic release

README.md
Correct package name in README
Wrong package name `ibmcloudantv0`
Correct package name `cloudantv1`
=> Correct package name in README

go.mod, go.sum
Fixes: #8 
go-sdk-core dependency is at `v4.0.8`
go-sdk-core dependency will be `v4.3.0`
=> Update go-sdk-core to 4.3.0

README.md
Add pre-release disclaimer to README
No disclaimer present.
Pre-release disclaimer in README.
=> docs: Add pre-release disclaimer to README

.travis.yml, README.md
=> Update go version to 1.15

go.mod, go.sum
Update go core version from 4.3.0 to 4.5.0
Update language version from 1.14 to 1.15
* Set the expected language version for the module to 1.15
* resolve path params by name, not by parameter ordering
* IAM Authenticator: add support for optional 'scope' property
* iam/cp4d token refresh logic
* expose AuthenticationError.Err field and add ctor
=> Update core version to 4.5.0 and language to 1.13

common/common_suite_test.go, common/headers_test.go
Rewrite header unit tests
Introduce new common suite file
Thanks to this change properly formatted junit reports could be generated during Jenkins pipeline runs.
For testing common package, the go framework provided tool is used.
The `Ginkgo` test framework is introduced like in package `cloudantv1`.
Also this will be used to generate junit reports for the Jenkins pipeline.
=> In common package change test framework to Gingko

common/common_suite_test.go
In Jenkins pipeline in the end the reporter will be set by command line option.
The junit generation is coded into common suite file.
The junit report will be called through cli option.
=> Remove Junit reporter from common suite

go.mod, go.sum
Fixes: #29 
`go-sdk-core` dependency is at version 4.5.0
`go-sdk-core` dependency updated to 4.7.0
=> Update core dependency to 4.7.0

.travis.yml
Enable codecov.io code coverage.
Reference: https://github.com/codecov/example-go#travis-setup
=> Enable codecov.io

README.md, examples/src/create_db_and_doc/create_db_and_doc.go, examples/src/delete_doc/delete_doc.go, examples/src/get_info_from_existing_database/get_info_from_existing_database.go, examples/src/update_doc/update_doc.go
- Change var name in `get_info_from_existing_database.go` and README examples from `examplesClient` to `client` for consistency with the rest of the examples.
- Update default service name in `create_db_and_doc` example
Fixes: #35 
=> Update examples for consistency

README.md, examples/src/create_db_and_doc/create_db_and_doc.go, examples/src/delete_doc/delete_doc.go, examples/src/update_doc/update_doc.go
The README had some links that pointed at external URLs about other authentication modes rather than env var configuration but it was not so obvious that includes the programmatic auth mode as well. The aim of this PR to highlight those links by creating a new section for them.
I also considered it is time to refactor the README file a little because the lines were getting longer and longer, and it was tough to read the lines at maintenance/review. The long links now also have a reference instead of inline linking. I was trying to keep the <80 char/line length, I broke this rule only if an inseparable link was in that line.
I put full stop where it was not before, and fixed some grammar issues.
I also found some markdown linting  and go fmt issues:
* missing whitespaces from the beginning …
=> Make link to programmatic auth more obvious

.travis.yml
_Temporarily_ disable race checking because new generated test code is causing CI failures that are blocking updates.
Travis CI fails because of races in new generated test code.
Disable race detection in Travis CI until we can get a fix from upstream for the generated test code.
The problem has been reported upstream and this change will be reverted as soon as a fix is available.
=> ci: temporarily remove race detection from travis

.golangci.yml, auth/auth_suite_test.go, auth/couchdb_session_authenticator.go, auth/couchdb_session_authenticator_test.go, auth/session.go, auth/session_test.go, cloudantv1/cloudant_v1_integration_test.go, common/common_suite_test.go, common/headers.go, common/headers_test.go, common/version.go, config/header-template.txt, examples/src/create_db_and_doc/create_db_and_doc.go, examples/src/delete_doc/delete_doc.go, examples/src/get_info_from_existing_database/get_info_from_existing_database.go, examples/src/update_doc/update_doc.go
The header checks right now are using exact text matches which is not flexible.
This commit refactors that check into a regex check so that it becomes more flexible.
See above.
See above.
=> Switch header checks to regex

auth/couchdb_session_authenticator.go, auth/couchdb_session_authenticator_test.go, go.mod, go.sum
Relates to: #88 
Currently `go-sdk-core` v4.10.0 is in use.
go-sdk-core v5.0.0 should be used.
This PR introduce `v5` into the dependencies and uses it in the session authenticator files.
=> Update go-sdk-core to v5.0.0 in custom files

cloudantv1/cloudant_v1_integration_test.go, go.mod, go.sum
Fixes: #88 
No behaviour change.
Removes remaining `go-sdk-core/v4` dependencies
From this PR the `cloudant-go-sdk` will use only `go-sdk-core/v5`. From this major version update, there could be incompatibility issues with `go-sdk-core/v4`.
=> Remove all go-sdk-core/v4 dependency

auth/couchdb_session_authenticator_test.go
Auth test "Test authentication refresh" occasionally fails due to async nature of the refresh mechanism. We are running three refresh clients in parallel with an assumption that the refresh process is slow enough for all of them to spawn before it finishes.
This proven to be unreliable, leading to a flaky test, so this change makes sure that we are testing only _first_ of the refresh clients to confirm that it is starting the refresh process asynchronously and then observing req counter to make sure we are calling our test server only once.
Fixes: #99
[Angular Commit Message …
=> Stabilize auth refresh tests

.travis.yml
Currently we are not getting any benefit from the `codecov` integration and  due to [a recent security incident](https://about.codecov.io/security-update/?utm_medium=email&utm_source=marketo&ajs_uid=&ajs_event=Clicked%20Email&mkt_tok=MzMyLUxWWC03NDEAAAF8dJnGkNG_ojrjdXL2M-fOtB8t5IIphrIeLMth6mxIfuhPHB7b_FDof-GXtPcIc5fc754EGZ-_sxnLPdyBwLd1yNBoppIr0iZuG9A5_FAL) we decided to remove it.
=> ci: remove codecov install and execution

.travis.yml
Relates to: #134 
The latest Go version is not supported yet officially.
Go 1.16 now is a supported version.
From now on only the last 2 version of Go will be supported.
=> Update supported go version to 15 and 16.

README.md
Fixes #134
Automated PR triggered by new code generation.
Update generated source code
Generated SDK source code using:
- Generator version 3.30.0
- Specification version 1.0.0-dev0.0.35
- Automation (cloudant-sdks) version dbd1f78
=> Update generated source code

examples/src/update_doc/update_doc.go
Fixes: <! -- link to issue -->
Add stream handling examples in note comments to update document example.
=> Add streaming notes to update example file

.secrets.baseline
Fixes: <! -- link to issue -->
=> ci: Add secrets baseline file and exclude all stubs json files

.travis.yml
Narrow scope of `go test` run in travis to stop tests from trying to run across new `examples` code snippets.
=> Narrow scope of `go test` run in travis

.github/workflows/test.yml
Disable persisting the actions token
`persist-credentials: true` the default for checkout action
`persist-credentials: false`
The actions don't need to run any other `git` commands.
=> ci: disable persisting the actions token

common/headers.go
goclilint fail on common/headers.go with File is not goimports-ed
Fixes: #300
Linter's failing with "File is not goimports-ed"
Linter's passing
=> fix: Invalid comments formatting in common headers

test/examples/output/get_info_from_existing_database.txt, test/examples/src/get_info_from_existing_database/get_info_from_existing_database.go
Update get_info examples to remove refs to deprecated examples.cloudant.com
=> docs: docs: update get_info examples

.github/workflows/test.yml
Sec it tighten around github actions, so remove lint step from actions for now.
Fixes: #376
=> Temporary remove linter step from actions

.github/workflows/test.yml
Action `golangci/golangci-lint-action` got approved for use by compliance, so adding it back int o CI
Fixes: #376 
- x ] No
=> Add linter back

features/changes_follower.go, features/changes_follower_suite_test.go, features/changes_follower_test.go, features/changes_follower_test_fixtures.go, test/examples/src/changes_follower/initialize.go, test/examples/src/changes_follower/start.go, test/examples/src/changes_follower/start_and_process.go, test/examples/src/changes_follower/start_one_off.go, test/examples/src/changes_follower/start_one_off_and_process.go, test/examples/src/changes_follower/stop.go
Add changes follower feature.
Users have to call `PostChanges` repeatedly and handle various transient errors or disconnects.
The feature adds a helper to automatically paginate the changes feed and return the changes in a channel. It also suppresses transient exceptions and retries (though this can be disabled).
=> feat: changes follower

.github/workflows/test.yml, go.mod
=> chore: update go versions to [1.20,1.21]

.github/workflows/docs.yml, .github/workflows/test.yml
We are getting deprecation warnings on our CI runs on using outdated actions. This update to fix that.
=> ci(chore): update actions checkout and setup-go in github workflows

.golangci.yml
Remove obsolete linter's checks
Fixes: #475 
=> chore: remove obsolete linter's checks

examples/snippets/go.mod, go.mod, test/examples/src/changes_follower/go.mod
=> Fix CodeQL alerts

.github/workflows/test.yml
Update `golangci-lint-action` to v6 to remove warnings on outdated node version.
Fixes: #518 
=> chore: bump golangci-lint-action version

go.mod
=> build: update go version to 1.22 with toolchain

.github/workflows/docs.yml, .github/workflows/test.yml, go.mod
Update Go minimum version to `1.23`
Fixes: part of s1125
Go minimum version is `1.22` (now EOL)
Go minimum version is `1.23`
Update CI version matrix to remove `1.22` and add `1.24`
=> chore: update Go minimum version to 1.23

.github/workflows/docs.yml, .github/workflows/test.yml, go.mod
Update the minimum supported Go version to 1.24
Fixes: part of s1223
Go 1.23 minimum
Tests on Go 1.23 and 1.24
Docs on Go 1.23
Go 1.24 minimum
Remove tests on Go 1.23, add tests for Go 1.25
Docs on Go 1.25
=> Go 1.25 version updates
