IBM/cloudant-go-sdk

- README.md
- examples/src/create_db_and_doc/create_db_and_doc.go
- examples/src/delete_doc/delete_doc.go
- examples/src/get_info_from_existing_database/get_info_from_existing_database.go
- examples/src/update_doc/update_doc.go
- Update struct literals to initializers
- Remove `SetContentType` from code examples as content-type now
explicitly set by `PostDocument` operaton when Document body is present
Fixes: #6 
Readme recommends explicit setter for content-type on a doc update
Remove the explicit setter
For the reference, automatic set of content-type on [`client.PostDocument`](https://github.com/IBM/cloudant-go-sdk/blob/master/cloudantv1/cloudant_v1.go#L961)
> Update code examples

- KNOWN_ISSUES.md
Since the `headers` parameters in the request bodies must be used as `HeadersVar` in Golang to prevent collision with the request headers (that are `Headers` in the Go-wrapped request), it is good to have a section about this different behavior in the KNOWN_ISSUES.
> Add headers to KNOWN_ISSUES

- .gitignore
- auth/couchdb_session_authenticator.go
- auth/couchdb_session_authenticator_test.go
- auth/session.go
This PR fixes three issues
The auth package's using two mutexes: one on `syncRequestSession` operation of authenticator module and another on modification of `refreshTime` in session. Since it's totally possible to have more then one authenticator (and consequently more than one session) instance in an app, the mutexes need to be local to the instances, otherwise they might introduce intermittent global blocking across all the service instances.
This is detected as a race by the tests, but only because we are testing `syncRequestSession` concurrently. In reality it's more of an issue with `CouchDbSessionAuthenticator` not to be thread-safe, because it's possible to do reading of `session` in `getCookie` in one thread while updating it during `requestSession` call in the other.
While we …
> Fix race in async session refresh and make getCookie a thread-safe operation

- .travis.yml
Reverts IBM/cloudant-go-sdk#58
Draft pending upstream fix of generated test code.
> Revert "ci: temporarily remove race detection from travis"

- auth/couchdb_session_authenticator.go
- auth/couchdb_session_authenticator_test.go
In `go-sdk-core` v5.6.0 constant `DEFAULT_CONTENT_TYPE` was removed breaking our couch auth module.
This PR sets content-type in auth request explicitly to fix that.
Also ginkgo 2.0 introducing new breaking changes removing async tests and the tests were throwing a deprecation warnings, so the tests were updated according to [migration guide](https://github.com/onsi/ginkgo/blob/v2/docs/MIGRATING_TO_V2.md#removed-async-testing) to remediate that.
> Explicitly set content-type in couch auth request and fix tests deprecation warnings

- .secrets.baseline
- common/cloudant_base.go
- common/cloudant_base_test.go
- common/testdata/my-credentials.env
Support a env var name alias `AUTHTYPE` for `AUTH_TYPE` to keep core's compatibility
Env var of format `SERVICE_AUTHTYPE` is ignored and error thrown on missing required variable
Env var of format `SERVICE_AUTHTYPE` accepted as a valid variable same as `SERVICE_AUTH_TYPE`
> Support alias env var AUTHTYPE

- common/cloudant_base_test.go
Add a test to validate that we are stripping a trailing slash on setting of service URL. The test for env file is not necessary, since in go-core slash stripped at later stage during request build.
> Validate trailing slash stripped on request build

- common/cloudant_base.go
Common User-Agent format across sdks should be `cloudant-<lang>-sdk/<sdk_version> (<lang>.version=<value>; [<lang>.vendor=<value>]; os.name=<value>; os.version=<value>; os.arch=<value>; lang=<lang>;)`
This PR adds trailing semicolon in sysinfo attributes list in User-Agent header.
Fixes: #251 
> Add missing semicolon in User-Agent header

- examples/src/create_db_and_doc/create_db_and_doc.go
- examples/src/delete_doc/delete_doc.go
- examples/src/update_doc/update_doc.go
The goal of this PR is to improve the description of `_rev`/`rev` requirements for post/put document. I also tried to explain where `_id`/`docId` is necessary similarly to `_rev`/`rev`.
I decided to use `/*...code is here...*/` for code comments and ornamentation lines before and after the explanation plus the commented out codes because with this way maybe the eyes can catch what belongs to what. Something like this:
```
// ========================================================================
// Note: the next code bla bla bla..:
/*
code is here
*/
// ========================================================================
```
I removed sub-points in the examples, to align with the other examples in other libs.
I fixed the timestamp in the example to a valid format. 
Please make sure …
> docs: improve description of rev requirements for post/put document

- .travis.yml
- go.mod
Fixes: #242 
Golang minimum version is 1.16 
Update minimum supported Golang version to 1.17
> Update Golang version to 1.17

- common/cloudant_base.go
- common/cloudant_base_test.go
add missing operation names to path validator
**Note: An existing issue is [required](https://github.com/IBM/cloudant-java-sdk/blob/main/CONTRIBUTING.md#PRs) before opening a PR.**
Not all operations have paths validated
Validate paths additionally on
`getDocumentAsMixed`
`getDocumentAsRelated`
`getDocumentAsStream`
migration path: any applications which use special paths for the above operations should use the correct operation, eg one of the `*AllDocs*` methods in the case of the `_all_docs` path.
> fix: add missing operation names to path validator

- .secrets.baseline
- common/cloudant_base.go
- common/cloudant_base_test.go
- common/testdata/my-credentials.env
Change our customized client instantiation to check for the presence of a Jar on the `HttpClient` and add one if one is not present for all auth types.
Cookie jar does not exist in auth types
Cookie jar enabled in all auth types
Added tests:
- Verify cookie jar is present in the service object for all auth types
- Verify custom client with cookie jar is enabled
> Enable cookie jar for all auth types

- .secrets.baseline
- auth/couchdb_session_authenticator.go
- auth/couchdb_session_authenticator_test.go
- auth/session.go
- auth/session_test.go
- common/cloudant_base.go
- common/cloudant_base_test.go
- go.mod
This refactoring makes CouchDB Session authenticator to use cookiejar to store authsession cookie and set it to requests and makes `BaseService` to set its HTTP client as client for CouchDB Session authenticator to share its cookiejar.
This is motivated by changes in CouchDB where server now sets auth session cookie on basic auth.
> Refactor session auth to use cookie jar and share base service http client

- auth/couchdb_session_authenticator.go
- auth/couchdb_session_authenticator_test.go
A race was introduced in #399 where a cookie read for clients with no cookiejar set was happening outside of the read lock. This PR makes sure we are reading cookie in the same thread that refreshes it.
Fixes: #406 
> fix: race in session auth's cookie refresh

- features/changes_follower_test_fixtures.go
Safer parsing of string representing limit into `int32` in follower's text fixtures, that's mindful of upper bound.
Query string parsed with `strconv.Atoi`
Query string pared with `strconv.ParseUint` with `bitSize` explicitly set to 32
> fix(test): safe parsing of string into int32 in tests fixtures

- go.mod
Latest two major releases of Go are supported.  This PR drops `1.20` and adds `1.21` as minimum version in `go.mod`.
https://tip.golang.org/doc/devel/release#policy
> chore: update go.mod version to 1.21

- features/changes_follower.go
- features/changes_follower_test.go
In the latest release `github.com/IBM/go-sdk-core/v5/core` added a wrapper around returned errors and that broke our error suppression for context related errors in changes follower. This PR restores that functionality. 
Fixes: #467 
> fix: supression of context errors in changes follower's runner

- features/changes_follower.go
- features/changes_follower_test.go
In changes follower it is possible to read from a closed changes channel and get an empty `ChangesItem` as a result. This is expected behaviour in golang by itself, but we have a method `Item()` on `ChangesItem` and calling it on an empty `ChangesItem` returns no error and empty `cloudantv1.ChangesResultItem` which can be confusing.
This PR changes this behaviour and returns an error "can't read from a closed channel" instead, based on assumption that there are no other way to actual get an empty `ChangesItem` from changes channel.
Fixes: #471 
[Angular Commit Message …
> fix: return an error on reading ChangesItem from a closed channel

- .github/workflows/docs.yml
- .github/workflows/test.yml
- auth/couchdb_session_authenticator.go
Set GOTOOLCHAIN to local in Github Actions to ensure that we are testing with expected go version.
Update:
Also a fix for a new linter error for new rule added in a latest version of `golangci-lint`
> ci: set GOTOOLCHAIN to local

- .github/workflows/docs.yml
- .github/workflows/test.yml
- go.mod
* Update GHA workflow matrix to include 1.23 and remove 1.21.
* Latest two major releases of Go are supported. This PR drops 1.21 and adds 1.22.7 as minimum version in `go.mod`.
https://tip.golang.org/doc/devel/release#policy
> Update go versions to the range of 1.22, 1.23

- base/cloudant_base.go
- base/cloudant_base_test.go
- base/error_response_transport.go
This PR adds a new RoundTripper to augment error messages and adds it to http client in middleware fashion at creation of  BaseService or at SetHTTPClient call.
The change covered by new test suite.
> feat: improve error responses

- base/cloudant_base_test.go
- base/error_response_transport.go
If the x-request-id header is on a response use it to set the error trace field (in preference to x-couch-request-id, but still use x-couch-request-id if there is no x-request-id).
Fixes: part of s1037
> feat: set x-request-id as error trace

- base/cloudant_base.go
- base/cloudant_base_test.go
- cloudantv1/cloudant_v1.go
Fixes: s1043
The SDK cannot unmarshal whole float numbers as `4.0` as `int64` for `ranges` and `counts` of the `SearchResult` and `SearchResultProperties` objects and fails with unmarshal error.
An interim layer unmarshals numbers to `float64`, then marshals it to a byte array that can be unmarshalled to `int64` without any failures.
Unmarshalling fractions is still not supported.
> fix: add modifications on ranges and counts for SearchResult and SearchResultProperties

- features/changes_follower.go
- features/changes_follower_test.go
Use normal feed mode for changes follower one-off FINITE mode.
Fixes: s1115 / i445
Currently the changes follower uses `longpoll` feed type is for both start (`LISTEN`) and `startOneOff` (`FINITE`) cases.
Switch to use the `normal` feed type for `startOneOff` (`FINITE`) mode to avoid waiting unnecessarily till timeout on empty feeds.
> refactor(follower): use normal feed for one-off changes
